name: primeira-pipeline-001
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow !!!"
          echo "Parabens"
      - name: "Script Python"
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 20.17.0 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: "Verificação da versão do NodeJS depois de instalar"
        run: node --version
        
      
        
    
          
          
